name: IP Camera Mock CI/CD

on:
  push:
    branches: [main]

jobs:
  build_push_docker:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:

      - uses: actions/checkout@v3

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ezequielmr94/ip-camera-mock
          tags: latest
